export const en = {
  emptyBacklog: "Your backlog is empty.",
  emptySprint: "Plan a sprint by dragging the sprint footer down below some issues, or by dragging issues here.",
  createSprint: "Create Sprint",
  startSprint: "Start Sprint",
  completeSprint: "Complete Sprint",
  deleteComment: "Delete Comment",
  deleteCommentOk: "Successfully deleted comment!",
  deleteCommentErr: "Failed to delete comment!",
  delete: "Delete",
  save: "Save",
  cancel: "Cancel",
  yes: "Yes",
  edit: "Edit",
  newest: "Newest first",
  oldest: "Oldest first",
  activity: "Activity",
  comments: "Comments",
  commentPlaceholder: "Write your comment here...",
  confirmDelete: "Are you sure you want to delete this comment?",
  description: "Descriptions",
  details: "Details",
};